docs/examples/main_demo.py

Use f-string because support for 3.5 was dropped and no reason not to.

Use f-string in main_demo code example

---

arq/testing.py
tests/test_utils.py

I tried to use MockRedis for unit tests and found out that there are no implementation for some functions.

Add missing functions for MockRedis

---

HISTORY.rst
arq/connections.py
tests/test_worker.py

prevent duplicate jobs when result exists

---

HISTORY.rst
arq/connections.py
arq/jobs.py
arq/worker.py
docs/examples/custom_serialization_msgpack.py
docs/index.rst
tests/conftest.py
tests/requirements.txt
tests/test_jobs.py
tests/test_main.py
tests/test_utils.py
tests/test_worker.py

I would like to propose this change, which allows the user to specify custom serializers in alternative to pickle, which is left as the default.
The public API is changed only very slightly: there are new `_serialize` and `_deserialize` arguments to `create_pool` and `Worker`. The rest of the changes essentially reduces to passing these to the pickle functions.
For backward compatibility, I have left the `pickle_jobs`, etc. functions in `arq.jobs` with the same name, even though the name is slightly inappropriate now.
The main reason I am proposing this change is to allow better memory usage. The default serialization method, pickle, is quite space inefficient. Since the job data is essentially JSON, we can attain much better memory usage by switching to serialization methods that are …

Custom serializers

---

HISTORY.rst
arq/worker.py
tests/conftest.py
tests/test_worker.py

This PR adds a new parameter to the `Worker` class: `queue_read_limit`. It allows limiting the number of job IDs that are read from the queue at each polling interval.
Redis requires to set both `offset` and `count`, so I've added another instance attribute called `queue_read_offset` that sets the offset to 0 in case `queue_read_limit` is specified, and to `None` otherwise. I haven't added a corresponding parameter for this attribute because I think that in the majority of the cases it's not needed. I think it could be useful to investigate it in case multiple workers are run in parallel, but I haven't tested this so I refrained from complicating the public interface further.
This PR passes all tests except two, which also fail in the `master` branch. So they are most likely unrelated to …

Feat worker limit

---

HISTORY.rst
arq/worker.py
tests/test_worker.py

**What**:
Fix abort_job `ERR invalid expire time in setex` on keep_result 0.
```
Traceback (most recent call last):
File ".../.venv/bin/arq", line 10, in <module>
sys.exit(cli())
File ".../.venv/lib/python3.7/site-packages/click/core.py", line 764, in __call__
return self.main(*args, **kwargs)
File ".../.venv/lib/python3.7/site-packages/click/core.py", line 717, in main
rv = self.invoke(ctx)
File ".../.venv/lib/python3.7/site-packages/click/core.py", line 956, in invoke
return ctx.invoke(self.callback, **ctx.params)
File "/.../.venv/lib/python3.7/site-packages/click/core.py", line 555, in invoke
return callback(*args, **kwargs)
File ".../.venv/lib/python3.7/site-packages/arq/cli.py", line 45, in cli
run_worker(worker_settings, **kwargs)
File …
```

Fix abort_job invalid expire time in setex

---

HISTORY.rst
arq/worker.py
tests/test_cron.py

**Why**:
Cron is not working correct when worker was started with a specific `queue_name`.
**What:**
Use the worker `queue_name` when enqueue cron jobs.
Sorry that I so late noticed that a similar fix is already in progress, added original issuer as co-author for my PR. Anyway feel free to close this one.
Co-authored-by: Tin Tvrtković <tinchester@gmail.com>

Fix cron scheduling on a specific queue

---

HISTORY.rst
arq/connections.py
tests/test_jobs.py

This will allow working with job objects when a non-default queue is specified.
```
j = arq.enqueue_job(TK, _queue_name='new queue')
status = await j.status()
```
Right now the object provided in response to `enqueue_job` uses the `default_queue_name`.
I will write up tests and update HISTORY tomorrow morning.
Hope you have a good weekend!

Include queue_name when returning job object after performing enqueue_job

---

arq/connections.py

`None` is a valid value for the password prop in `RedisSettings`

Make password setting Optional[str] for RedisSettings

---

HISTORY.rst
arq/version.py
arq/worker.py
tests/test_worker.py

replace #170
The point here is that each worker needs to get more job ids from the queue than it's able to run in case some of those jobs are already running.
This problem will have been introduced by #142

fix concurrency with multiple workers

---

HISTORY.rst
arq/utils.py

Fixes passing a `datetime` without time zone information to `_defer_until` being assumed to be at utc and this incorrectly deferring the task.
The issue can be replicated with this code. Just switch between lines 2-3 in the `main()`. If the computer's timezone is not utc this will be an issue.
```
import asyncio
from datetime import datetime, timedelta, timezone
from arq import create_pool
from arq.connections import RedisSettings
def utc_to_local(utc_dt):
return utc_dt.replace(tzinfo=timezone.utc).astimezone(tz=None)
async def task(ctx, due_date):
print("***************** New Task ***************")
print(f"The task was enqueued at {utc_to_local(ctx['enqueue_time'])}")
print(f"With due date {utc_to_local(due_date)}")
print(f"and the time is {datetime.now()}")
async def main():
redis = …
```

Use builtin timestamp and fix timezone issues

---

HISTORY.rst
arq/connections.py
arq/utils.py
arq/worker.py
tests/conftest.py
tests/test_jobs.py
tests/test_main.py

When using a single central Redis with multiple services, it's necessary to use different queues.
It's cumbersome to have to pass the queue name when enqueing jobs all the time, so we add the ability for an instance of ArqRedis to remember it.
We also make the worker be able to get the default queue name from ArqRedis, to not have to repeat ourselves.
This should be backwards compatible.
I've also fixed some timezone issues which were failing tests on my machine, which is not in UTC.

Introduce default queue name to ArqRedis

---

HISTORY.rst
arq/worker.py

`asyncio.gather` makes no guarantees about the order of execution of the coroutines it's given, and in this case ordering matters (the unwatch needs to execute before the watch, for example). So I've explicitly broken out the gather into individual awaits, then wrapped the awaits in a pipeline for less I/O.

Remove gather

---

arq/jobs.py
arq/worker.py
tests/test_jobs.py

This pull request addresses issue #161 
I didn't feel like I needed to add any new tests as modifying the existing tests checks that the attribute exists in the result.
Also technically I could add the queue_name attribute in the JobDef as well but I don't really see a use for that yet but happy to add it there as well.

Added queue_name attribute to JobResult

---

arq/worker.py

The issue was encountered when initializing redis through RedisSettings
instead of explicitly setting the arq connection pool.
If cron was used and `job_serializer` was not `pickle` the cron item would be
serialized with pickle.dumps and then attempted to deserialize with the configured
`job_deserializer` in worker, causing an error.
Quick workaround is to create the pool yourself, otherwise always use the
pickle serializer.

Fix issue where pool serializer would not be same as worker

---

docs/index.rst

Just a small fix in the start of the tutorial

Fix coroutine name in docs

---

docs/examples/custom_serialization_msgpack.py
docs/examples/deferred.py
docs/examples/job_ids.py
docs/examples/job_results.py
docs/examples/main_demo.py
docs/examples/retry.py
docs/examples/slow_job.py

Avoids the `Task was destroyed but it is pending!` error message. Looks a little neater too.

Use asyncio.run() in examples

---

arq/worker.py
tests/test_main.py

This fixes an issue where custom serializers are not used if the job is enqueued from the ctx within an existing task.

Fix to allow custom serializers

---

arq/cron.py
arq/worker.py
tests/test_worker.py

I tried adding yet another "if None" condition to `keep_result` but it quickly became too hard to manage.
Instead, I opted for adding a new option to Worker/Function that can be used to toggle the expiry off.
Fixes #204

Feature: allow keeping results forever

---

arq/constants.py
arq/cron.py
arq/worker.py
tests/test_cron.py

This is an attempt of fixing #196.
Instead of enqueueing a cron job after the cron time, we enqueue before.
This makes the cron job run closer to its schedule, and the enqueues are idempotent (it's the same if one worker enqueues or 20).
A more detailed explanation follows.
We introduce the concept of a cron scheduling window, that's tied to the polling delay (the polling delay default is 0.5s), except the cron scheduling window length is clamped at a minimum value of 0.5s. Anyway, let's assume the poll delay is 0.5s, and hence the cron window length is 0.5s.
We start keeping track of the exact time of the last heartbeat.
On each heartbeat, we iterate over the defined cronjobs, choose cronjobs that are inside the window and enqueue them. The window is defined as starting at …

Cron refactor

---

arq/jobs.py
arq/worker.py

As issue #190 noted, `except Exception as e` doesn't catch an `asyncio.CancelledError`. Some of the code in `Worker` clearly expects `asyncio.CancelledError` to be caught properly if raised in a `Job`. This PR fixes the appropriate lines to catch the error properly instead of kicking it all the way out to the enclosing Worker task, which then gets cancelled.

Fix Worker and Job to catch CancelledException.

---

HISTORY.rst
arq/constants.py
arq/jobs.py
arq/worker.py
docs/examples/job_abort.py
docs/index.rst
setup.py
tests/requirements.txt
tests/test_worker.py

Added method to cancel jobs through a new `abort()` function on Job. This allows long-running or deferred jobs to be cancelled.
This is a cleanup of PR #173 , since the submitter didn't finish the requested changes, with one design change: a `Worker` will cancel aborted jobs by default. I made the design change so that people aren't surprised when they call `abort()` on a `Job` and nothing happens. My guess is that it's more common to want to allow cancelling jobs than to block that operation.
This addresses issue #172 .

Add method to cancel jobs

---

setup.py

arq is currently breaking because, it now installs aioredis 2.0.0 and this version is not compatible as errors are now changed to exceptions and so on...

fix: arq is incompatible for aioredis>=2.0.0

---

.github/workflows/ci.yml
arq/worker.py
tests/test_worker.py

Currently on job timeout  there is log message: `job_name cancelled, will be run again` and job is restarted immediately.
This PR fixes it: `TimeoutError` is logged and job is not restarted. (see #247)

Fix jobs timeout

---

arq/worker.py

Looks like the `queue_read_limit` argument was described correctly when initially introduced in https://github.com/samuelcolvin/arq/pull/142, but that the default value was later changed to fix an issue (in https://github.com/samuelcolvin/arq/pull/180) without the docstring being updated.

Update argument docstring definition

---

docs/examples/main_demo.py

A minor detail I'd like to add to the docs. Obviously not necessary, but it took me longer than I'd like to admit to troubleshoot why the worker would not start (I had connection startup configured in my `startup` function instead) :smile:

Add link to WorkerSettings in documentation

---

arq/connections.py
tests/test_utils.py

This PR adds the ability to pass the `username` option to the Redis connection

Add the username option to RedisSettings

---

arq/cli.py
tests/requirements-linting.txt
tests/test_cli.py

This points at an import path for a dictionary (e.g. myproject.logging.CONFIG_DICT) that Arq can configure its logging with instead of using the default configuration.
This would be useful for e.g. configuring Arq logging output to use [python-json-logger](https://github.com/madzak/python-json-logger).
We use this in a fork of Arq for a project I'm working on, and I wanted to contribute this back upstream. I'm happy to make any changes that are needed.

Add --custom-log-dict CLI option

---

arq/utils.py

This small change fixes the crash In case of not installed `pytz`.
Here is example errors traceback:
`Traceback (most recent call last):
File ".../main.py", line 14, in <module>
import arq.cli
File "....../venv/lib/python3.9/site-packages/arq/__init__.py", line 1, in <module>
from .connections import ArqRedis, create_pool  # noqa F401
File "....../venv/lib/python3.9/site-packages/arq/connections.py", line 18, in <module>
from .jobs import Deserializer, Job, JobDef, JobResult, Serializer, deserialize_job, serialize_job
File "....../venv/lib/python3.9/site-packages/arq/jobs.py", line 13, in <module>
from .utils import ms_to_datetime, poll, timestamp_ms
File "....../venv/lib/python3.9/site-packages/arq/utils.py", line 38, in <module>
def get_tz() -> Optional[pytz.BaseTzInfo]:
AttributeError: …

Fix: crash in case of not installed pytz

---

arq/connections.py

The existing description for `_expires` does not make it clear how retried jobs are handled
and what is the default behavior when `_expires` is not set.
For example, if a job which had the first attempt within expiry and a second attempt after
expiry, does it mean that it "still hasn't started"?

Improve docs for parameter _expires in enqueue_job

---

arq/connections.py
arq/constants.py
arq/worker.py
tests/test_worker.py

Currently, `expires_extra_ms` in arq/connections.py sets a default expiry of 1 day from when a job was expected to start to when it would expire if no expiry was set in `enqueue_job()`.
Our project found we needed that to be longer, so we made it configurable as part of both ArqRedis and Worker, as `.default_job_expiry`.
This PR also moves `expires_extra_ms` to arq/constants.py along with other shared constants.
----
`default_job_expiry` might not be the best name for this option, as it's one of a few different job expiry times, so I'm happy to rename the option as necessary.

Allow user to configure a default job expiry-extra length

---

arq/jobs.py
tests/test_worker.py

There is an issue when aborting a deferred task. 
Currently when you abort a deferred task, the worker will wait until the deferred time is met to properly perform the delete.
This behaviour make it complicated to perform test that implicate canceling a deferred task.
I implemented a way to update the score of the deferred task when aborting it, but may be there is a better way to do this.

Support abort for deferred tasks

---

arq/worker.py
tests/test_worker.py

It is not always desirable to include job result in logs.
This PR is one of the possible solutions to #349, where logging results can be suppressed by setting the new `Worker.log_results` flag to false.

Allow to opt-out from logging results

---

arq/worker.py
tests/test_cron.py
tests/test_worker.py

This changeset ensures that calculations of execution time for cron jobs are done on timezone-aware datetime objects. Timezone can be specified by a new `Worker` attribute `timezone` which defaults to the system timezone (which preserves the current behavior).
Fixes: #351

Add timezone support for cron jobs

---

arq/connections.py

Potential fix for: https://github.com/redis/redis-py/issues/2407

connections: fix pipeline usage for exists command

---

arq/jobs.py

Checking job status consited of three separate calls to Redis, where the first one checked if result is present and the second checked if job is in progress. If a job got completed between these two calls Job.status() would erroneously return status not_found.
The solution is to make all the calls to Redis in one transaction.
Fixes #329

Fix race condition causing incorrect status not_found

---

arq/worker.py
tests/test_worker.py

Adds an additional hook for after the job completes. Useful for doing something _after_ the results for the job has been recorded.
My specific use case is I am adding New Relic integration into arq for our projects. Being able to record the success/failure, queue time, etc. of a job directly to New Relic is very useful.

Adds after_job_end hook

---

arq/worker.py
tests/test_worker.py

First commit proves the bug (see the pipeline failures [here](https://github.com/samuelcolvin/arq/actions/runs/3628698559))  
Second commit contains the fix. 
Closes #369

Prevent worker getting stuck in terminating state

---

arq/jobs.py

Fixes a mistake introduced in #364 where a Redis pipeline was created but not used (ArqRedis is used directly).
The pipeline was there to prevent race conditions, so it should be used.

Fix redis pipeline created and not used

---

arq/connections.py

I think it would be less surprising for `queued_jobs` to default to the instance's default rather than the global default.

Use instance's default queue for queued_jobs default

---

docs/index.rst

Example usage. This will clear finished jobs 60s after they complete, after which you could reuse that job_id on a new job
```py
arq.run_worker(WorkerSettings, keep_result=60)
```
See: 
* https://github.com/samuelcolvin/arq/pull/138#issuecomment-523589365
* https://github.com/samuelcolvin/arq/issues/221

Docs: Add details about reusing a unique job id

---

arq/worker.py
tests/test_worker.py

**Issue** #405  
Having a semaphore in the same event loop, while having the max number of jobs running, blocks heartbeat & cancellation tasks.
**Possible solution**
* Keep the semaphore value to `max_jobs + 1`
* Have a `job_counter` that increments when the semaphore is acquired and decrements when the semaphore is released
* If the `job_counter == max_jobs`, release the semaphore immediately and return from the `start_jobs` function, basically foregoing starting new jobs.
The solution seems to work. The counter is threadsafe because we always increment or decrement it **before** releasing the semaphore. Quick test app below:
* Define the worker definition in `arq_app.py`
* Start 4 workers in different processes from `start_workers.py`
* Schedule more jobs than max for each worker from …

🔨 Adding a job counter to address Semaphore issues

---

arq/connections.py
arq/jobs.py
arq/worker.py
tests/test_jobs.py
tests/test_main.py

This probably need a good review. I looked at the discussion in #198, which had a good reason to use `.get('id')` over `d['id']`. 
Close #376

feat: add job_id to JobDef, closing #376

---

arq/connections.py
arq/cron.py
arq/worker.py

Close #371 
Can be closed if #371 is not accepted.

refactor: refactor all asserts into raise <exception>, close #371

---

arq/cron.py
tests/test_cron.py

This PR fixes a bug where timezone information was occasionally removed from execution time of cron jobs. The bug affected cron jobs which used the month-rule and when month was incremented due to that rule.
Since #354 all cron calculations are done on timezone aware datetimes. However, the tests for `next_cron` function were not updated to include timezone in all test cases, which is how the bug slipped through. The tests are updated now to always use timezone.
Fixes: #380

Fix: timezone info occasionally removed from cron job execution time

---

arq/connections.py

In some contexts (cluster) it is useful to allow infinite retries `float('inf')`. Especially in clusters redis might be not available for some time but we don't want the worker to crash on that. Instead it just should wait until redis comes available again.
`float('inf')` always compare greater than any float or int. So it should be safe to use. But `str(float('inf'))` translates to `'inf'` and that's why this change is necessary.

Allow infinite retry

---

.github/workflows/ci.yml
.pre-commit-config.yaml
arq/typing.py
arq/utils.py
docs/examples/main_demo.py
pyproject.toml
requirements/pyproject.txt

The actual uprev happened in 918ea716fd1ae8d270f807266dd09445a2893ee6 which I accidentally pushed to main, this is just some follow ups.

uprev to v0.26.0b1

---

arq/worker.py
tests/test_worker.py

Related issue:
https://github.com/python-arq/arq/issues/482

Fix race condition on task retry

---

arq/connections.py
arq/worker.py

Fix negative expires_ms and avoid worker freezing while using cron
