python-arq/arq

HISTORY.rst, Makefile, arq/main.py, arq/utils.py, arq/worker.py, setup.cfg, tests/fixtures.py, tests/requirements.txt, tests/test_cron.py, tests/test_utils.py
=> scheduled tasks

HISTORY.rst, arq/version.py, arq/worker.py, tests/conftest.py, tests/example.py, tests/test_worker.py
fix #47, see also https://github.com/MagicStack/uvloop/issues/94.
=> better signal handling

HISTORY.rst, arq/jobs.py, arq/main.py, arq/worker.py, tests/fixtures.py, tests/test_main.py, tests/test_worker.py
=> simplifying job encode and decode

.gitignore, HISTORY.rst, arq/connections.py, arq/jobs.py, arq/version.py, arq/worker.py, docs/examples/job_results.py, tests/test_jobs.py, tests/test_main.py, tests/test_worker.py
=> Pickle dicts

HISTORY.rst, arq/connections.py, tests/test_main.py
=> implement queued_jobs

HISTORY.rst, arq/jobs.py, arq/version.py, arq/worker.py, tests/test_jobs.py, tests/test_main.py, tests/test_worker.py
@rubik, some changes to deserialization. You might want to check this doesn't conflict with your usage of msgpack, it shouldn't but better to check.
=> better logic for deserializing

HISTORY.rst, arq/connections.py, arq/worker.py, tests/conftest.py, tests/test_main.py, tests/test_worker.py
=> handle multiexec errors

HISTORY.rst, setup.py
So mypy doesn't complain about missing imports :)
=> Add py.typed file

HISTORY.rst, arq/connections.py, tests/test_utils.py
This PR adds and opportunity to specify SSL options for making an encrypted connection between the client and Redis nodes.
=> Added the SSL option for RedisSettings dataclass

HISTORY.rst, arq/worker.py, tests/test_worker.py
Used when you want to listen to signal handlers on your own
Closes #182
=> Option to disable registration of signal handlers

docs/examples/sync_job.py, docs/index.rst
=> Add example for sync jobs to docs

arq/jobs.py, tests/test_jobs.py, tests/test_main.py, tests/test_worker.py
=> rename pole -> poll

.github/workflows/ci.yml, arq/connections.py, arq/version.py
fix #254
@smlbiobot @alextford11 can you test this and check somehow it's working with redis labs.
Install this PR with
```bash
pip install git+https://github.com/samuelcolvin/arq.git@log_redis_info
```
=> log_redis_info

arq/worker.py, tests/test_cron.py
=> fix error when cron jobs were terminanted

arq/cron.py, arq/worker.py, tests/test_cron.py
Closes #292 
I will add tests if you accept the feature.
=> Allow setting job_id on cron jobs

.github/workflows/ci.yml, setup.py, tests/conftest.py, tests/test_cli.py, tests/test_worker.py
=> support python 3.10

.github/workflows/ci.yml, HISTORY.rst, docs/requirements.txt, tests/requirements-linting.txt
preparing for release of v0.23 which is just a non-pre copy of v0.23a1.
=> add v0.23 history

arq/__init__.py
As it causes type hint problem
=> Remove noqa F401

docs/examples/sync_job.py
Added return statement in example `sync_job.py`
=> Added return statement in example `sync_job.py`

.github/workflows/ci.yml
hopefully make it a tiny bit faster.
=> tweak ci a little

.github/workflows/ci.yml
Also uprev python in linting and deploy jobs.
=> test against multiple redis versions

arq/worker.py, tests/test_worker.py
This is a draft in order to ask for feedback on implementation and to see if this is something that you would consider accepting before I look into tests (which I'm not sure how to do, honestly)
TODO: Write some proper docstrings, write tests and clean up log messages (haven't proof read anything)
=> feat: signal handler to wait for task completion before shutting down

docs/examples/job_ids.py
=> docs: add documentation on how to retrieve running jobs
